export const RELATIONSHIP_DATA_VERSION = "1.0.0";

export const RELATIONSHIP_DATA = {
  1: {
    name: "Companions",
    relationships: [
      "They have been through hell together before.",
      "They are close friends and confidants.",
      "They have similar hobbies or interests.",
      "They have an unspoken code of mutual protection.",
      "One is trying to corrupt the other.",
      "They trust each other with their lives.",
      "They serve as a moral compass for the other.",
      "They are thick as thieves.",
      "One reminds the other of a lost friend or family member.",
      "They have a pact to get back to civilization together, no matter what.",
    ],
  },
  2: {
    name: "Professional",
    relationships: [
      "They served together in the same unit or corporation.",
      "One is a mentor to the other.",
      "They cover for the other's mistakes.",
      "One got the job the other wanted.",
      "They are professional rivals in direct competition.",
      "One is clearly better at the job, and it's a sore point.",
      "They share complaints about management or the current assignment.",
      "They collaborated on a successful—and profitable—project.",
      "Their methods and philosophies clash constantly.",
      "They have a shared history of failing together.",
    ],
  },
  3: {
    name: "Romantic",
    relationships: [
      "They are secretly involved with each other.",
      "They are in a relationship together.",
      "They are former lovers, and it's still awkward.",
      "They had a bad breakup in their past.",
      "There is an unspoken attraction between them.",
      "They have a friends with benefits arrangement.",
      "They're stuck in a will-they-won't-they dynamic.",
      "They hooked up once, and it's complicated.",
      "One is trying to win the other back.",
      "They are trying to keep things strictly professional.",
    ],
  },
  4: {
    name: "Obligation & Debt",
    relationships: [
      "One saved the other's life, creating a life debt.",
      "One knows a deeply damaging secret about the other.",
      "One is blackmailing the other.",
      "They owe the same dangerous people or corporation money.",
      "One took the fall for the other's mistake or crime.",
      "There is an unresolved debt between them.",
      "They are bound by a past betrayal.",
      "One helped the other escape the law.",
      "They are caught in the same conspiracy.",
      "There is a major unspoken obligation between them.",
    ],
  },
  5: {
    name: "Rivalry",
    relationships: [
      "They have a begrudging mutual respect for each other.",
      "They are bitter enemies with a shared history.",
      "They are former friends turned rivals.",
      "They are in a friendly competition with each other.",
      "One is a one-sided rival, but the other is oblivious.",
      "They want what the other has.",
      "They compete over nearly everything.",
      "They are from opposing factions or organizations.",
      "They are forced to work together despite their animosity.",
      "One blames the other for a personal loss.",
    ],
  },
  6: {
    name: "Ambivalent",
    relationships: [
      "They have never really talked much, but are now stuck together.",
      "There is mutual indifference toward them.",
      "They run in different social circles, even on this ship.",
      "They know of each other, but that's it.",
      "One is actively avoiding the other.",
      "Something unspoken makes them awkward around each other.",
      "Their communication is stilted and formal.",
      "One is a minor celebrity to the other, but they don't know it.",
      "They have nothing in common to bond over.",
      "They get the feeling they’ve met before, but can’t place where.",
    ],
  },
  7: {
    name: "Shared Trauma",
    relationships: [
      "They are the only survivors of a past disaster.",
      "They both witnessed something they shouldn't have.",
      "One saved the other from a horrific monster.",
      "They survived the same corporate experiment.",
      "They share the memory of a crewmate’s death.",
      "They were both part of a failed mission with a high body count.",
      "They are bonded by a terrifying encounter from their past.",
      "They both suffer from a recurring nightmare from a shared event.",
      "One knows the other's most shameful secret.",
      "They are both running from the same past mistake.",
    ],
  },
  8: {
    name: "Unlikely Bond",
    relationships: [
      "One comes from privilege, the other from poverty.",
      "They are two vastly different people who found a mutual interest.",
      "One is the other’s hero, but they don’t know it.",
      "They are both hiding a secret from the rest of the crew.",
      "They constantly get on each other's nerves, but they work well together.",
      "They were rivals, but have since gained respect for one another.",
      "One is a jaded veteran, the other a naive rookie.",
      "They are united by a common enemy.",
      "They are the only ones who can perform a specific task together.",
      "One is the other's confidant for a secret they are both keeping.",
    ],
  },
};
